package use_cases.collaborative_task_management.collaborative_task_creation_use_case;

public interface CollaborativeTaskCreationInputBoundary {
    CollaborativeTaskCreationResponseModel create(CollaborativeTaskCreationRequestModel requestModel);
}